import { useMemo, useState } from 'react';
import { Header } from '../components/Header';
import { useAuth } from '../auth/AuthContext';
import { useTeacherProfiles, type Teacher } from './TeacherManagement';
import { getSalarySlipArchives, type SalarySlipArchive } from '../lib/teacherSalaryService';
import { getBranchName } from '../lib/branchService';
import { Download, FileText } from 'lucide-react';

export function TeacherSalarySlips() {
  const { user } = useAuth();
  const teachers = useTeacherProfiles();
  const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7));
  const archiveList = useMemo(() => {
    if (!user) return [] as SalarySlipArchive[];
    return getSalarySlipArchives({ teacherId: user.id, month: selectedMonth });
  }, [selectedMonth, user]);
  
  const selectedTeacher = useMemo(() => {
    return teachers.find((teacher) => teacher.id === user?.id);
  }, [teachers, user]);

  const downloadArchive = (archive: SalarySlipArchive) => {
    const link = document.createElement('a');
    link.href = `data:application/pdf;base64,${archive.base64Pdf}`;
    link.download = archive.fileName;
    link.click();
  };

  return (
    <div className="flex-1 bg-background">
      <Header title="My Salary Slips" />
      <div className="max-w-6xl mx-auto p-6 space-y-6">
        <div className="rounded-2xl border border-border bg-card p-6 shadow-sm">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <h1 className="text-xl font-bold text-foreground">My Salary Slip History</h1>
              <p className="mt-1 text-sm text-muted-foreground">Review archived salary slips for the selected month. Download payslips that were generated by the accountant.</p>
            </div>
            <div className="grid gap-2 sm:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium text-foreground">Month</label>
                <input type="month" className="w-full rounded-xl border border-input bg-input-background px-3 py-2 text-sm" value={selectedMonth} onChange={(event) => setSelectedMonth(event.target.value)} />
              </div>
            </div>
          </div>
        </div>

        {archiveList.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-border bg-secondary/30 p-8 text-center text-sm text-muted-foreground">
            No archived salary slips found for {selectedMonth}. Ask your accountant to generate and archive the salary slip.
          </div>
        ) : (
          <div className="grid gap-4">
            {archiveList.map((archive) => (
              <div key={archive.id} className="rounded-2xl border border-border bg-card p-5 shadow-sm flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Month</p>
                  <p className="text-lg font-semibold text-foreground">{archive.month}</p>
                  <p className="text-sm text-muted-foreground mt-2">Branch: {getBranchName(archive.branchId)}</p>
                  <p className="text-sm text-muted-foreground">Generated By: {archive.generatedBy} ({archive.generatedByRole})</p>
                  <p className="text-sm text-muted-foreground">Created At: {new Date(archive.createdAt).toLocaleString()}</p>
                </div>
                <button onClick={() => downloadArchive(archive)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground hover:bg-primary/90">
                  <Download className="h-4 w-4" /> Download Slip
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
